site:
  name: NTXIDB
  site: "https://ntxidb.com"
  base: "/"
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: NTXIDB
    template: "%s â€” NTXIDB"
  description: "We are a local marketing company in Rockwall, Texas. Premium marketing solutions including website design, social media management, and indoor billboard advertising."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: NTXIDB
    images:
      - url: "~/assets/images/default.png"
        width: 1200
        height: 628
    type: website
  twitter:
    handle: "@ntxidb"
    site: "@ntxidb"
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

ui:
  theme: "system" # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
